/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as AuthImport } from './../routes/_auth'
import { Route as IndexImport } from './../routes/index'
import { Route as DashboardDashboardImport } from './../routes/_dashboard/dashboard'
import { Route as DashboardDashboardIndexImport } from './../routes/_dashboard/dashboard.index'
import { Route as AuthLoginIndexImport } from './../routes/_auth/login/index'
import { Route as AuthLoginErrorImport } from './../routes/_auth/login/error'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardRoute = DashboardDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardIndexRoute = DashboardDashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardDashboardRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginErrorRoute = AuthLoginErrorImport.update({
  path: '/login/error',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/dashboard': {
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login/error': {
      preLoaderRoute: typeof AuthLoginErrorImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login/': {
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthImport
    }
    '/_dashboard/dashboard/': {
      preLoaderRoute: typeof DashboardDashboardIndexImport
      parentRoute: typeof DashboardDashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([AuthLoginErrorRoute, AuthLoginIndexRoute]),
  DashboardDashboardRoute.addChildren([DashboardDashboardIndexRoute]),
])

/* prettier-ignore-end */
